➜  recetas-app git:(main) ✗ gunicorn --bind 0.0.0.0:5002 kitchen.wsgi:application
[2025-09-15 17:44:15 -0500] [3463455] [INFO] Starting gunicorn 21.2.0
[2025-09-15 17:44:15 -0500] [3463455] [INFO] Listening at: http://0.0.0.0:5002 (3463455)
[2025-09-15 17:44:15 -0500] [3463455] [INFO] Using worker: sync
[2025-09-15 17:44:15 -0500] [3463456] [INFO] Booting worker with pid: 3463456
[2025-09-15 17:44:15 -0500] [3463456] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/almalinux/.local/lib/python3.9/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kitchen.wsgi'
[2025-09-15 17:44:15 -0500] [3463456] [INFO] Worker exiting (pid: 3463456)
[2025-09-15 17:44:15 -0500] [3463455] [ERROR] Worker (pid:3463456) exited with code 3
[2025-09-15 17:44:15 -0500] [3463455] [ERROR] Shutting down: Master
[2025-09-15 17:44:15 -0500] [3463455] [ERROR] Reason: Worker failed to boot.